<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="JIM-TI8227" name="CompleteTest" tests="12" failures="2" timestamp="30 Oct 2015 07:08:38 GMT" time="349.633" errors="0">
  <testcase name="Invalid_login_Test" time="36.92" classname="TestCases.LoginTestcase"/>
  <testcase name="Invalid_login_Test" time="26.639" classname="TestCases.LoginTestcase"/>
  <testcase name="Invalid_login_Test" time="24.132" classname="TestCases.LoginTestcase"/>
  <testcase name="Invalid_login_Test" time="24.479" classname="TestCases.LoginTestcase"/>
  <testcase name="Invalid_login_Test" time="24.131" classname="TestCases.LoginTestcase"/>
  <testcase name="Invalid_login_Test" time="22.574" classname="TestCases.LoginTestcase"/>
  <testcase name="valid_login" time="24.024" classname="TestCases.LoginTestcase"/>
  <testcase name="Invalid_booksearch" time="19.206" classname="TestCases.BookSearch_TestCase"/>
  <testcase name="valid_booksearch" time="22.372" classname="TestCases.BookSearch_TestCase">
    <failure type="java.lang.AssertionError" message="expected [430] but found [415]">
      <![CDATA[java.lang.AssertionError: expected [430] but found [415]
	at TestCases.BookSearch_TestCase.valid_booksearch(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- valid_booksearch -->
  <testcase name="valid_booksearch" time="50.975" classname="TestCases.BookSearch_TestCase"/>
  <testcase name="valid_booksearch" time="24.816" classname="TestCases.BookSearch_TestCase">
    <failure type="java.lang.AssertionError" message="expected [495] but found [492]">
      <![CDATA[java.lang.AssertionError: expected [495] but found [492]
	at TestCases.BookSearch_TestCase.valid_booksearch(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- valid_booksearch -->
  <testcase name="add2Cart" time="47.933" classname="TestCases.BookCart_TestCase"/>
</testsuite> <!-- CompleteTest -->
